name: Build and Deploy to AWS S3

on:
  push:
    branches:
      - main # change to your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: [15.x] # use your preferred Node version

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
          bucket: ${{ secrets.AWS_S3_BUCKET }} # set this in your repo's secrets
          path: ./build/
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }} # set this in your repo's secrets
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} # set this in your repo's secrets
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # set this in your repo's secrets
          AWS_REGION: "eu-central-1" # change to your AWS region
